[at]
debug = 1
close.on.exit = 1
start.minimized = 1

free.side.select = 1
livecpk.enabled = 1

;start.game = "steam://rungameid/1259970"
exe.name = "\PES2021.exe"

; enforce number of match minutes here
; you can set any value from 1 to 255, although you probably
; do not want to go higher than 90, because it will be weird :-)
; 0 - disables this feature.
match.minutes = 0

; to see mstats.at working, set this to 1
match-stats.enabled = 1

cpk.root = ".\at\ball-root"

; Lua settings
lua.enabled = 1
luajit.ext.enabled = 1

lua.module = "at_tracker.at"
lua.module = "set_teams.at"
;lua.module = "env.at"
;lua.module = "etrace.at"
;lua.module = "camera.at"
;lua.module = "jittest.at"
;lua.module = "trophy.at"
;lua.module = "zlibtest.at"
;lua.module = "cr7_audio.at"
;lua.module = "overlay_colors_test.at"
;lua.module = "netblock.at"
;lua.module = "pointers.at"
;lua.module = "mstats.at"
;lua.module = "timeaccel.at"
;lua.module = "matchset.at"
;lua.module = "tracer.at"
;lua.module = "inputdemo.at"
;lua.module = "snow.at"
;lua.module = "facedump.at"
;lua.module = "filedump2.at"
;lua.module = "kitrewrite.at"
;lua.module = "gc64test.at"

; Overlay settings
; location on screen: top|bottom
; size of the font (0 - automatic)
; overlay hot keys: 
; 0x20 - [space] - toggle overlay on/off
; 0x31 - [1] - pass overlay control to next module
; 0xc0 - [~] - pass overlay control to previous module
; colors are in RRGGBBAA format
overlay.enabled = 1
overlay.on-from-start = 0
overlay.location = "top"
overlay.font-size = 0
overlay.font = "Lucida Console"
overlay.vkey.toggle = 0x20
overlay.vkey.next-module = 0x31
overlay.vkey.prev-module = 0xc0
overlay.background-color = "07182ba0"
overlay.text-color = "28b8ffc0"
overlay.image-alpha-max = 0.6
overlay.toggle.sound = "toggle.wav"
overlay.toggle.sound-volume = 0.2
overlay.block-input-when-on = 0
window.hidden = 0

; Reload modified modules
; Default combination: Shift-R
vkey.reload-1 = 0x10
vkey.reload-2 = 0x52

